refactor index finding aid job to use traject API
mlibrary/umich-arclight pull request #84
Opened 2023-03-10 19:21 UTC by gkostin1966

2023-03-10 19:50 UTC, botimer requested changes

2023-03-10 20:10 UTC, gkostin1966 commented on app/jobs/index_finding_aid_job.rb
> +      # A Traject reader which reads XML, and yields zero to many Nokogiri::XML::Document
Reduce comments to essentials

2023-03-10 21:30 UTC, respinos approved these changes

2023-03-10 21:30 UTC, respinos commented on lib/dul_arclight/traject/ead2_config.rb
> +    if record_output.length > 500
Oh thank heavens.

2023-04-05 19:17 UTC, gkostin1966 commented
Rolled in to PR #91

2023-04-05 19:17 UTC, closed without merging